### ISSUE TITLE
Freezing Player Not Working in Nether, tracking not working in nether

### ISSUE THREAD

**Issue by Rismose** [NateKomodo/DreamManHunt#23]
## Some information
Operating system (client): Windows 10
Java version (client): Java 8
Operating system (server): Linux Ubuntu 18.04
Java version (server): Java 11
Minecraft version: 1.16.5
Plugin version: 1.2.1
Forge mods (if used): 
Other plugins (if used): 

## Exception, error or logs
Please find your `latest.log` attach it to the issue
`[17:09:36] [main/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[17:09:37] [main/INFO]: Reloading ResourceManager: Default, bukkit
[17:09:37] [Worker-Main-3/INFO]: Loaded 7 recipes
[17:09:39] [Server thread/INFO]: Starting minecraft server version 1.16.5
[17:09:39] [Server thread/INFO]: Loading properties
[17:09:39] [Server thread/INFO]: This server is running Paper version git-Paper-542 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
[17:09:39] [Server thread/INFO]: Debug logging is disabled
[17:09:39] [Server thread/INFO]: Server Ping Player Sample Count: 12
[17:09:39] [Server thread/INFO]: Using 4 threads for Netty based IO
[17:09:39] [Server thread/INFO]: Default game type: SURVIVAL
[17:09:39] [Server thread/INFO]: Generating keypair
[17:09:39] [Server thread/INFO]: Starting Minecraft server on 0.0.0.0:25566
[17:09:39] [Server thread/INFO]: Using epoll channel type
[17:09:40] [Server thread/INFO]: [Assassin] Loading Assassin v1.2.1
[17:09:40] [Server thread/INFO]: Server permissions file permissions.yml is empty, ignoring it
[17:09:40] [Server thread/INFO]: Preparing level "world"
[17:09:40] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld
[17:09:40] [Server thread/INFO]: Loaded 0 spawn chunks for world world
[17:09:40] [Server thread/INFO]: Preparing spawn area: 0%
[17:09:40] [Server thread/INFO]: Preparing spawn area: 0%
[17:09:41] [Server thread/INFO]: Time elapsed: 729 ms
[17:09:41] [Server thread/INFO]: Preparing start region for dimension minecraft:the_nether
[17:09:41] [Server thread/INFO]: Loaded 0 spawn chunks for world world_nether
[17:09:41] [Server thread/INFO]: Preparing spawn area: 0%
[17:09:41] [Server thread/INFO]: Preparing spawn area: 0%
[17:09:42] [Server thread/INFO]: Preparing spawn area: 7%
[17:09:42] [Server thread/INFO]: Time elapsed: 1447 ms
[17:09:42] [Server thread/INFO]: Preparing start region for dimension minecraft:the_end
[17:09:42] [Server thread/INFO]: Loaded 0 spawn chunks for world world_the_end
[17:09:42] [Server thread/INFO]: Preparing spawn area: 0%
[17:09:42] [Worker-Main-5/INFO]: Preparing spawn area: 100%
[17:09:42] [Server thread/INFO]: Time elapsed: 507 ms
[17:09:42] [Server thread/INFO]: [Assassin] Enabling Assassin v1.2.1
[17:09:43] [Server thread/INFO]: [Assassin] Assassin plugin started.
[17:09:43] [Server thread/INFO]: Running delayed init tasks
[17:09:43] [Server thread/INFO]: Done (4.488s)! For help, type "help"
[17:09:43] [Server thread/INFO]: Timings Reset
[17:09:51] [User Authenticator #1/INFO]: UUID of player Filicks is 8f8e2e18-b2a3-4ec8-a238-808078a2bb78
[17:09:51] [Server thread/INFO]: Filicks joined the game
[17:09:52] [Server thread/INFO]: Filicks[/redacted:57487] logged in with entity id 371 at ([world]45.83014500236341, 82.0, 51.47443489662293)
[17:10:03] [User Authenticator #1/INFO]: UUID of player Rismose is 78159c17-e341-424d-939d-30128b0eeb24
[17:10:04] [Server thread/INFO]: Rismose joined the game
[17:10:04] [Server thread/INFO]: Rismose[/redacted:3538] logged in with entity id 411 at ([world]162.5617548485795, 63.0, 121.67392737993379)
[17:10:08] [Server thread/INFO]: Rismose issued server command: /team
[17:10:09] [Server thread/INFO]: Rismose issued server command: /teams
[17:10:14] [Server thread/INFO]: Rismose issued server command: /manhunt
[17:10:26] [Server thread/INFO]: Rismose issued server command: /kill Rismose
[17:10:26] [Server thread/INFO]: Rismose fell out of the world
[17:10:26] [Server thread/INFO]: [Rismose: Killed Rismose]
[17:10:36] [Server thread/INFO]: Rismose issued server command: /time set day
[17:10:36] [Server thread/INFO]: [Rismose: Set the time to 1000]
[17:11:02] [Server thread/INFO]: Rismose issued server command: /butcher
[17:11:16] [Server thread/INFO]: Rismose has made the advancement [Monster Hunter]
[17:11:19] [Server thread/INFO]: Rismose issued server command: /kill Rismose
[17:11:19] [Server thread/INFO]: Rismose fell out of the world
[17:11:19] [Server thread/INFO]: [Rismose: Killed Rismose]
[17:11:21] [Server thread/INFO]: Filicks fell from a high place
[17:11:42] [Server thread/INFO]: Rismose issued server command: /assassin
[17:11:53] [Server thread/INFO]: Rismose issued server command: /speedrunner rismose
[17:12:02] [Server thread/INFO]: Rismose issued server command: /assassin Filicks
[17:12:32] [Server thread/INFO]: Rismose fell from a high place
[17:09:36] [main/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[17:09:37] [main/INFO]: Reloading ResourceManager: Default, bukkit
[17:09:37] [Worker-Main-3/INFO]: Loaded 7 recipes
[17:09:39] [Server thread/INFO]: Starting minecraft server version 1.16.5
[17:09:39] [Server thread/INFO]: Loading properties
[17:09:39] [Server thread/INFO]: This server is running Paper version git-Paper-542 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
[17:09:39] [Server thread/INFO]: Debug logging is disabled
[17:09:39] [Server thread/INFO]: Server Ping Player Sample Count: 12
[17:09:39] [Server thread/INFO]: Using 4 threads for Netty based IO
[17:09:39] [Server thread/INFO]: Default game type: SURVIVAL
[17:09:39] [Server thread/INFO]: Generating keypair
[17:09:39] [Server thread/INFO]: Starting Minecraft server on 0.0.0.0:25566
[17:09:39] [Server thread/INFO]: Using epoll channel type
[17:09:40] [Server thread/INFO]: [Assassin] Loading Assassin v1.2.1
[17:09:40] [Server thread/INFO]: Server permissions file permissions.yml is empty, ignoring it
[17:09:40] [Server thread/INFO]: Preparing level "world"
[17:09:40] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld
[17:09:40] [Server thread/INFO]: Loaded 0 spawn chunks for world world
[17:09:40] [Server thread/INFO]: Preparing spawn area: 0%
[17:09:40] [Server thread/INFO]: Preparing spawn area: 0%
[17:09:41] [Server thread/INFO]: Time elapsed: 729 ms
[17:09:41] [Server thread/INFO]: Preparing start region for dimension minecraft:the_nether
[17:09:41] [Server thread/INFO]: Loaded 0 spawn chunks for world world_nether
[17:09:41] [Server thread/INFO]: Preparing spawn area: 0%
[17:09:41] [Server thread/INFO]: Preparing spawn area: 0%
[17:09:42] [Server thread/INFO]: Preparing spawn area: 7%
[17:09:42] [Server thread/INFO]: Time elapsed: 1447 ms
[17:09:42] [Server thread/INFO]: Preparing start region for dimension minecraft:the_end
[17:09:42] [Server thread/INFO]: Loaded 0 spawn chunks for world world_the_end
[17:09:42] [Server thread/INFO]: Preparing spawn area: 0%
[17:09:42] [Worker-Main-5/INFO]: Preparing spawn area: 100%
[17:09:42] [Server thread/INFO]: Time elapsed: 507 ms
[17:09:42] [Server thread/INFO]: [Assassin] Enabling Assassin v1.2.1
[17:09:43] [Server thread/INFO]: [Assassin] Assassin plugin started.
[17:09:43] [Server thread/INFO]: Running delayed init tasks
[17:09:43] [Server thread/INFO]: Done (4.488s)! For help, type "help"
[17:09:43] [Server thread/INFO]: Timings Reset
[17:09:51] [User Authenticator #1/INFO]: UUID of player Filicks is 8f8e2e18-b2a3-4ec8-a238-808078a2bb78
[17:09:51] [Server thread/INFO]: Filicks joined the game
[17:09:52] [Server thread/INFO]: Filicks[/redacted:57487] logged in with entity id 371 at ([world]45.83014500236341, 82.0, 51.47443489662293)
[17:10:03] [User Authenticator #1/INFO]: UUID of player Rismose is 78159c17-e341-424d-939d-30128b0eeb24
[17:10:04] [Server thread/INFO]: Rismose joined the game
[17:10:04] [Server thread/INFO]: Rismose[/redacted:3538] logged in with entity id 411 at ([world]162.5617548485795, 63.0, 121.67392737993379)
[17:10:08] [Server thread/INFO]: Rismose issued server command: /team
[17:10:09] [Server thread/INFO]: Rismose issued server command: /teams
[17:10:14] [Server thread/INFO]: Rismose issued server command: /manhunt
[17:10:26] [Server thread/INFO]: Rismose issued server command: /kill Rismose
[17:10:26] [Server thread/INFO]: Rismose fell out of the world
[17:10:26] [Server thread/INFO]: [Rismose: Killed Rismose]
[17:10:36] [Server thread/INFO]: Rismose issued server command: /time set day
[17:10:36] [Server thread/INFO]: [Rismose: Set the time to 1000]
[17:11:02] [Server thread/INFO]: Rismose issued server command: /butcher
[17:11:16] [Server thread/INFO]: Rismose has made the advancement [Monster Hunter]
[17:11:19] [Server thread/INFO]: Rismose issued server command: /kill Rismose
[17:11:19] [Server thread/INFO]: Rismose fell out of the world
[17:11:19] [Server thread/INFO]: [Rismose: Killed Rismose]
[17:11:21] [Server thread/INFO]: Filicks fell from a high place
[17:11:42] [Server thread/INFO]: Rismose issued server command: /assassin
[17:11:53] [Server thread/INFO]: Rismose issued server command: /speedrunner rismose
[17:12:02] [Server thread/INFO]: Rismose issued server command: /assassin Filicks
[17:12:32] [Server thread/INFO]: Rismose fell from a high place

`

## How to reproduce
Add your steps to reproduce the issue/bug experienced here.

Be in nether with the appropriate config settings turned on

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have filled in all the sections.
- [x] I have included logs, exceptions and / or steps to reproduce the issue.

**Comment by NateKomodo** [comment]
I cannot recreate freezing not working in the nether [video](https://streamable.com/sxdtom)

As for compass tracking, please see #14 as this is the expected behaviour

**Comment by NateKomodo** [comment]
Are you sure you ran the `/assasin` command to reload the config after changing the freeze setting to true?

**Comment by Rismose** [comment]
> Are you sure you ran the `/assasin` command to reload the config after changing the freeze setting to true?

I'm pretty sure I did, I even forked it and made my own version, I'll recheck if it works or not and come back to you.

**Comment by NateKomodo** [comment]
Stale issue. Will re-open if author provides further info.
